if(NOT DEFINED MVDSV_SOURCE_DIR)
	message(FATAL_ERROR "MVDSV_SOURCE_DIR is required")
endif()

file(READ "${MVDSV_SOURCE_DIR}/src/sv_init.c" startup)
string(FIND "${startup}" "void SV_SpawnServer" begin)
string(FIND "${startup}" "#endif // !CLIENTONLY" end)
math(EXPR length "${end} - ${begin}")
string(SUBSTRING "${startup}" ${begin} ${length} spawn_server)
foreach(forbidden IN ITEMS "ED_FindFieldOffset" "QCX_ResolveOptionalEntityFields")
	string(FIND "${spawn_server}" "${forbidden}" position)
	if(NOT position EQUAL -1)
		message(FATAL_ERROR "SV_SpawnServer must not discover optional entity fields")
	endif()
endforeach()

file(READ "${MVDSV_SOURCE_DIR}/src/pr_optional_fields.c" legacy)
file(READ "${MVDSV_SOURCE_DIR}/src/qcx/entities.c" qcx)
foreach(name IN ITEMS items2 maxspeed gravity movement vw_index hideentity trackent visclients hideplayers teleported)
	if(NOT legacy MATCHES "ED_FindFieldOffset\\(\\\"${name}\\\"\\)")
		message(FATAL_ERROR "legacy discovery is missing ${name}")
	endif()
	if(NOT qcx MATCHES "\\\"${name}\\\"")
		message(FATAL_ERROR "QCX fixed matrix is missing ${name}")
	endif()
endforeach()
