if(NOT DEFINED MVDSV_SOURCE_DIR)
	message(FATAL_ERROR "MVDSV_SOURCE_DIR is required")
endif()

file(READ "${MVDSV_SOURCE_DIR}/src/sv_init.c" startup)
string(FIND "${startup}" "void SV_SpawnServer" begin)
string(FIND "${startup}" "#endif // !CLIENTONLY" end)
math(EXPR length "${end} - ${begin}")
string(SUBSTRING "${startup}" ${begin} ${length} spawn_server)
foreach(forbidden IN ITEMS "ED_FindFieldOffset" "QCX_ResolveOptionalEntityFields")
	string(FIND "${spawn_server}" "${forbidden}" position)
	if(NOT position EQUAL -1)
		message(FATAL_ERROR "SV_SpawnServer must not discover optional entity fields")
	endif()
endforeach()

if(EXISTS "${MVDSV_SOURCE_DIR}/src/pr_optional_fields.c")
	message(FATAL_ERROR "legacy optional-field discovery must live in src/pr_edict.c")
endif()

file(READ "${MVDSV_SOURCE_DIR}/src/pr_edict.c" legacy)
file(READ "${MVDSV_SOURCE_DIR}/src/qcx/entities.c" qcx)
foreach(name IN ITEMS items2 maxspeed gravity movement vw_index hideentity trackent visclients hideplayers teleported)
	if(NOT legacy MATCHES "\\{\\\"${name}\\\", &fofs_")
		message(FATAL_ERROR "legacy optional-field table is missing ${name}")
	endif()
	if(NOT qcx MATCHES "\\\"${name}\\\"")
		message(FATAL_ERROR "QCX fixed matrix is missing ${name}")
	endif()
endforeach()

if(NOT legacy MATCHES "void PR_ResetOptionalFieldOffsets\\(void\\)")
	message(FATAL_ERROR "pr_edict.c must provide the shared optional-field reset")
endif()
if(NOT legacy MATCHES "ED_FindFieldOffset\\(pr_optional_fields\\[index\\]\\.name\\)")
	message(FATAL_ERROR "legacy optional-field resolver must discover every table entry")
endif()
