/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#ifndef __PROGDEFS_H__
#define __PROGDEFS_H__

/* file generated by qcc, do not modify */

#define PROGHEADER_CRC 54730

typedef struct
{	int	pad[28];
	int	self;
	int	other;
	int	world;
	float	time;
	float	frametime;
	int	newmis;
	float	force_retouch;
	string_t	mapname;
	float	serverflags;
	float	total_secrets;
	float	total_monsters;
	float	found_secrets;
	float	killed_monsters;
	float	parm1;
	float	parm2;
	float	parm3;
	float	parm4;
	float	parm5;
	float	parm6;
	float	parm7;
	float	parm8;
	float	parm9;
	float	parm10;
	float	parm11;
	float	parm12;
	float	parm13;
	float	parm14;
	float	parm15;
	float	parm16;
	vec3_t	v_forward;
	vec3_t	v_up;
	vec3_t	v_right;
	float	trace_allsolid;
	float	trace_startsolid;
	float	trace_fraction;
	vec3_t	trace_endpos;
	vec3_t	trace_plane_normal;
	float	trace_plane_dist;
	int	trace_ent;
	float	trace_inopen;
	float	trace_inwater;
	int	msg_entity;
	func_t	main;
	func_t	StartFrame;
	func_t	PlayerPreThink;
	func_t	PlayerPostThink;
	func_t	ClientKill;
	func_t	ClientConnect;
	func_t	PutClientInServer;
	func_t	ClientDisconnect;
	func_t	SetNewParms;
	func_t	SetChangeParms;
} globalvars_t;

#ifdef QCX_ENABLED
#include "game/shared_entity_state.h"
#include "game/shared_global_state.h"
#include <stddef.h>

typedef qcx_shared_entity_state_v1_t entvars_t;

_Static_assert(sizeof(entvars_t) == QCX_SHARED_ENTITY_STATE_V1_SIZE,
	"qc2cpp entity size");
_Static_assert(_Alignof(entvars_t) == QCX_SHARED_ENTITY_STATE_V1_ALIGN,
	"qc2cpp entity alignment");
_Static_assert(offsetof(entvars_t, health) == QCX_SHARED_ENTITY_STATE_OFFSET_HEALTH,
	"qc2cpp entity health");
_Static_assert(offsetof(entvars_t, enemy) == QCX_SHARED_ENTITY_STATE_OFFSET_ENEMY,
	"qc2cpp entity enemy");
_Static_assert(offsetof(entvars_t, model) == QCX_SHARED_ENTITY_STATE_OFFSET_MODEL,
	"qc2cpp entity model");
_Static_assert(offsetof(entvars_t, netname) == QCX_SHARED_ENTITY_STATE_OFFSET_NETNAME,
	"qc2cpp entity netname");
_Static_assert(PROGHEADER_CRC == QCX_SHARED_ENTITY_STATE_PROGHEADER_CRC,
	"qc2cpp entity ABI CRC");

_Static_assert(sizeof(globalvars_t) == sizeof(qcx_shared_global_state_v1_t),
	"qc2cpp globals size");
_Static_assert(_Alignof(globalvars_t) == _Alignof(qcx_shared_global_state_v1_t),
	"qc2cpp globals alignment");
#define QCX_ASSERT_GLOBAL_OFFSET(field, shared_field) \
	_Static_assert(offsetof(globalvars_t, field) == offsetof(qcx_shared_global_state_v1_t, shared_field), \
		"qc2cpp global " #field)
QCX_ASSERT_GLOBAL_OFFSET(self, self);
QCX_ASSERT_GLOBAL_OFFSET(other, other);
QCX_ASSERT_GLOBAL_OFFSET(world, world);
QCX_ASSERT_GLOBAL_OFFSET(time, time);
QCX_ASSERT_GLOBAL_OFFSET(frametime, frametime);
QCX_ASSERT_GLOBAL_OFFSET(newmis, newmis);
QCX_ASSERT_GLOBAL_OFFSET(force_retouch, force_retouch);
QCX_ASSERT_GLOBAL_OFFSET(mapname, reserved_mapname);
QCX_ASSERT_GLOBAL_OFFSET(serverflags, serverflags);
QCX_ASSERT_GLOBAL_OFFSET(total_secrets, total_secrets);
QCX_ASSERT_GLOBAL_OFFSET(total_monsters, total_monsters);
QCX_ASSERT_GLOBAL_OFFSET(found_secrets, found_secrets);
QCX_ASSERT_GLOBAL_OFFSET(killed_monsters, killed_monsters);
QCX_ASSERT_GLOBAL_OFFSET(parm1, parm1);
QCX_ASSERT_GLOBAL_OFFSET(parm16, parm16);
QCX_ASSERT_GLOBAL_OFFSET(v_forward, v_forward);
QCX_ASSERT_GLOBAL_OFFSET(v_up, v_up);
QCX_ASSERT_GLOBAL_OFFSET(v_right, v_right);
QCX_ASSERT_GLOBAL_OFFSET(trace_allsolid, trace_allsolid);
QCX_ASSERT_GLOBAL_OFFSET(trace_startsolid, trace_startsolid);
QCX_ASSERT_GLOBAL_OFFSET(trace_fraction, trace_fraction);
QCX_ASSERT_GLOBAL_OFFSET(trace_endpos, trace_endpos);
QCX_ASSERT_GLOBAL_OFFSET(trace_plane_normal, trace_plane_normal);
QCX_ASSERT_GLOBAL_OFFSET(trace_plane_dist, trace_plane_dist);
QCX_ASSERT_GLOBAL_OFFSET(trace_ent, trace_ent);
QCX_ASSERT_GLOBAL_OFFSET(trace_inopen, trace_inopen);
QCX_ASSERT_GLOBAL_OFFSET(trace_inwater, trace_inwater);
QCX_ASSERT_GLOBAL_OFFSET(msg_entity, msg_entity);
#undef QCX_ASSERT_GLOBAL_OFFSET
#else
typedef struct
{
	float	modelindex;
	vec3_t	absmin;
	vec3_t	absmax;
	float	ltime;
	float	lastruntime;
	float	movetype;
	float	solid;
	vec3_t	origin;
	vec3_t	oldorigin;
	vec3_t	velocity;
	vec3_t	angles;
	vec3_t	avelocity;
	string_t	classname;
	string_t	model;
	float	frame;
	float	skin;
	float	effects;
	vec3_t	mins;
	vec3_t	maxs;
	vec3_t	size;
	func_t	touch;
	func_t	use;
	func_t	think;
	func_t	blocked;
	float	nextthink;
	int	groundentity;
	float	health;
	float	frags;
	float	weapon;
	string_t	weaponmodel;
	float	weaponframe;
	float	currentammo;
	float	ammo_shells;
	float	ammo_nails;
	float	ammo_rockets;
	float	ammo_cells;
	float	items;
	float	takedamage;
	int	chain;
	float	deadflag;
	vec3_t	view_ofs;
	float	button0;
	float	button1;
	float	button2;
	float	impulse;
	float	fixangle;
	vec3_t	v_angle;
	string_t	netname;
	int	enemy;
	float	flags;
	float	colormap;
	float	team;
	float	max_health;
	float	teleport_time;
	float	armortype;
	float	armorvalue;
	float	waterlevel;
	float	watertype;
	float	ideal_yaw;
	float	yaw_speed;
	int	aiment;
	int	goalentity;
	float	spawnflags;
	string_t	target;
	string_t	targetname;
	float	dmg_take;
	float	dmg_save;
	int	dmg_inflictor;
	int	owner;
	vec3_t	movedir;
	string_t	message;
	float	sounds;
	string_t	noise;
	string_t	noise1;
	string_t	noise2;
	string_t	noise3;
} entvars_t;
#endif

#endif /* !__PROGDEFS_H__ */
